### ISSUE TITLE
The bounding box is not showing

### ISSUE THREAD

**Issue by isaacgbhk** [daved01/DetectorAppSwiftUI#1]
Thanks for the tutorial, first of all!!! This is the best video about drawing real-time bounding boxes, particularly using SwiftUI I have ever seen.

I built your original code with my iPad and found that the bounding box does not show which detector has output. And I have tried manually drawing a bounding box. But I can't see any.

Is there any hint for me? Thank you so much.

**Comment by isaacgbhk** [comment]
Oops, I finally find that the bounding boxes are in white colour and I can't see it with white BG lol. And I solved it by changing the RGB values of the box layer in Detector.swift - func drawBoundingBox.

###The RGB value should be 0.0 -1.0###

```
    func drawBoundingBox(_ bounds: CGRect) -> CALayer {
        let boxLayer = CALayer()
        boxLayer.frame = bounds

        boxLayer.borderWidth = 3.0
//        boxLayer.borderColor = CGColor.init(red: 7.0, green: 8.0, blue: 7.0, alpha: 1.0)
        boxLayer.borderColor = CGColor.init(red: 1.0, green: 1.0, blue: 0.0, alpha: 1.0)                <= This line
        boxLayer.cornerRadius = 4
        return boxLayer
    }
```

**Comment by daved01** [comment]
Thanks for pointing this out you are right. I've corrected it.
