### ISSUE TITLE
Video capture becomes fuzzy

### ISSUE THREAD

**Issue by zohairhadi** [daved01/DetectorAppSwiftUI#3]
When running the app, sometime the video feed become fuzzy.

![IMG_C3989B42E48D-1](https://user-images.githubusercontent.com/45510142/204999259-05ef3aac-d4a8-49c0-afb3-9a96a5691067.jpeg)

**Comment by daved01** [comment]
Thanks for the info. Please remember that this is tutorial code which is meant to explore basic concepts, not for good performance. 
You could for example change the resolution of the images which are fed to the detector etc.
